apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: routetable
spec:
  forProvider:
    region: us-east-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: internetgateway
    associations:
      - subnetIdRef:
          name: subnet-1
      # - subnetIdRef:
      #     name: subnet-2
    vpcIdRef:
      name: playground-vpc
  providerConfigRef:
    name: default
