apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: subnet-1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 10.0.0.0/24
    vpcIdRef:
      name: playground-vpc
    tags:
    - key: Name
      value: subnet-1
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default
