apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: playground-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Name
      value: playground-vpc
    instanceTenancy: default
  providerConfigRef:
    name: default
