apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: {{ .Values.subnet.name }}
spec:
  forProvider:
    region: {{ .Values.region }}
    availabilityZone: {{ .Values.subnet.availabilityZone }}
    cidrBlock: {{ .Values.subnet.cidrBlock }}
    vpcIdRef:
      name: {{ .Values.vpc.name }}
    tags:
    - key: Name
      value: {{ .Values.subnet.name }}
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
