apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: routetable
spec:
  forProvider:
    region: {{ .Values.region }}
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: {{ .Values.igwName }}
    associations:
      - subnetIdRef:
          name: {{ .Values.subnetName }}
      # - subnetIdRef:
      #     name: subnet-2
    vpcIdRef:
      name: {{ .Values.vpcName }}
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
